config/routes.rb
TaskManager::Application.routes.draw do
  resources :stories do
    resources :story_comments
    put :change_state
  end

  resources :users
  resource :session, :only => [:new, :create, :destroy]

end

app/models/story_comment.rb
class StoryComment < ActiveRecord::Base
  belongs_to :story
  attr_accessible :comment, :story_id, :user_id

  validates :comment,  :presence => true
  validates :story_id,  :presence => true
  validates :user_id,  :presence => true
end

app/controllers/story_comments_controller.rb
class StoryCommentsController < ApplicationController
  # GET /story_comments
  # GET /story_comments.json
  def index
    @story_comments = StoryComment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @story_comments }
    end
  end

  # GET /story_comments/1
  # GET /story_comments/1.json
  def show
    @story_comment = StoryComment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @story_comment }
    end
  end

  # GET /story_comments/new
  # GET /story_comments/new.json
  def new
    @story_comment = StoryComment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @story_comment }
    end
  end

  # GET /story_comments/1/edit
  def edit
    @story_comment = StoryComment.find(params[:id])
  end

  # POST /story_comments
  # POST /story_comments.json
  def create
    @story = Story.find(params[:story_id])
    @story_comment = @story.story_comments.new(params[:story_comment])
    @user = current_user
    @story_comment.user_id = @user.id 

    respond_to do |format|
      if @story_comment.save
        format.html { redirect_to story_path(@story), notice: 'Story comment was successfully created.' }
        format.json { render json: @story_comment, status: :created, location: @story_comment }
      else
        format.html { render action: "new" }
        format.json { render json: @story_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /story_comments/1
  # PUT /story_comments/1.json
  def update
    @story_comment = StoryComment.find(params[:id])

    respond_to do |format|
      if @story_comment.update_attributes(params[:story_comment])
        format.html { redirect_to @story_comment, notice: 'Story comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @story_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /story_comments/1
  # DELETE /story_comments/1.json
  def destroy
    @story = Story.find(params[:story_id])
    @story_comment = @story.story_comments.find(params[:id])
    @story_comment.destroy

    respond_to do |format|
      format.html { redirect_to story_path(@story) }
      format.json { head :no_content }
    end
  end
end

app/helpers/story_comments_helper.rb
module StoryCommentsHelper
end

app/views/story_comments/_form.html.haml
= simple_form_for(@story_comment) do |f|
  - if @story_comment.errors.any?
    #error_explanation
      %h2
        = pluralize(@story_comment.errors.count, "error")
        prohibited this story_comment from being saved:
      %ul
        - @story_comment.errors.full_messages.each do |msg|
          %li= msg
          
  .field
    = f.label :story_id
    %br/
    = f.number_field :story_id
  .field
    = f.label :user_id
    %br/
    = f.number_field :user_id
  .field
    = f.label :comment
    %br/
    = f.text_area :comment
  .actions
    = f.submit

app/views/story_comments/edit.html.haml
%h1 Editing story_comment
= render 'form'
= link_to 'Show', @story_comment
|
\#{link_to 'Back', story_comments_path}

app/views/story_comments/index.html.haml
%h1 Listing story_comments
%table
  %tr
    %th Story
    %th User
    %th Comment
    %th
    %th
    %th
  - @story_comments.each do |story_comment|
    %tr
      %td= story_comment.story_id
      %td= story_comment.user_id
      %td= story_comment.comment
      %td= link_to 'Show', story_comment
      %td= link_to 'Edit', edit_story_comment_path(story_comment)
      %td= link_to 'Destroy', story_comment, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Story comment', new_story_comment_path

app/views/story_comments/new.html.haml
%h1 New story_comment
= render 'form'
= link_to 'Back', story_comments_path

app/views/story_comments/show.html.haml
%p#notice= notice
%p
  %b Story:
  = @story_comment.story_id
%p
  %b User:
  = @story_comment.user_id
%p
  %b Comment:
  = @story_comment.comment
= link_to 'Edit', edit_story_comment_path(@story_comment)
|
\#{link_to 'Back', story_comments_path}