config/routes.rb
TaskManager::Application.routes.draw do
  resources :stories do
    resources :story_comments
    put :change_state
  end

  resources :users
  resource :session, :only => [:new, :create, :destroy]

end

app/models/story.rb
class Story < ActiveRecord::Base
  has_many :story_comments, :dependent => :destroy
  belongs_to :user
  
  attr_accessible :description, :state, :title, :user_id

  validates :description,  :presence => true
  validates :title,  :presence => true, :length => {:minimum => 1, :maximum => 254}
  validates :user_id,  :presence => true


  state_machine :state, initial: :new do
    event :start do
      transition :accepted => :started
    end

    event :finish do
      transition all => :finished
    end
  
    event :accept do
      transition [:new, :rejected] => :accepted
    end

    event :reject do
      transition :new => :rejected
    end

  end  
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  
  def change_state
    @story = Story.find(params[:story_id])
    if @story
      @story.fire_state_event(params[:event])
      @story.save
    end
    redirect_to stories_path
  end


  # GET /stories
  # GET /stories.json
  def index
    @q = Story.search(params[:q])

    if params[:q].nil?
      @stories = Story.all
    else
      @stories = @q.result(:distinct => true)
    end

     @stories = @q.result(:distinct => true)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stories }
    end
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
    @story = Story.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @story }
    end
  end

  # GET /stories/new
  # GET /stories/new.json
  def new
    @story = Story.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @story }
    end
  end

  # GET /stories/1/edit
  def edit
    @story = Story.find(params[:id])
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(params[:story])

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render json: @story, status: :created, location: @story }
      else
        format.html { render action: "new" }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stories/1
  # PUT /stories/1.json
  def update
    @story = Story.find(params[:id])

    respond_to do |format|
      if @story.update_attributes(params[:story])
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story = Story.find(params[:id])
    @story.destroy

    respond_to do |format|
      format.html { redirect_to stories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.haml
= simple_form_for @story do |f|
  - if @story.errors.any?
    #error_explanation
      %h2
        = pluralize(@story.errors.count, "error")
        prohibited this story from being saved:
      %ul
        - @story.errors.full_messages.each do |msg|
          %li= msg

  = f.input :title, :lable => "title"
  = f.input :description, :type => "text", :lable => "description"
  = f.hidden_field :user_id, :value => current_user.id
  = f.button :submit

app/views/stories/_search_form.html.haml
= search_form_for @q do |f|
  = f.collection_select :user_id_eq, User.all, :id, :login, {}, {:multiple => false}
  = f.collection_select :state_eq, Story.state_machine.states, :name, :name, {}, {:multiple => false}
  = f.submit

app/views/stories/edit.html.haml
%h1 Editing story
= render 'form'
= link_to 'Show', @story
|
\#{link_to 'Back', stories_path}

app/views/stories/index.html.haml
= render "search_form"
%h1 Listing stories
%table{ :class => "table table-striped"}
  %tr
    %th Title
    %th Description
    %th State
    %th User
    %th
    %th
    %th
  - @stories.each do |story|
    %tr
      %td= story.title
      %td= story.description
      %td= story.state
      %td= get_user_login(story.user_id)
      %td= link_to 'Show', story
      - if author?(story.user_id)
        %td= link_to 'Edit', edit_story_path(story)
        %td= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' }
      - else
        %td
        %td
%br/
- if signed_in?
  = link_to 'New Story', new_story_path

app/views/stories/new.html.haml
%h1 New story
= render 'form'
= link_to 'Back', stories_path

app/views/stories/show.html.haml
%p#notice= notice
%p
  %b Title:
  = @story.title
%p
  %b Description:
  = @story.description
%p
  %b State:
  = @story.state
%p
  %b User:
  = get_user_login(@story.user_id)

- if author?(@story.user_id)
  = link_to "Начать выполнение", story_change_state_path(@story, event: :start), method: :put if @story.can_start?
  = link_to "Завершить выполнение", story_change_state_path(@story, event: :finish), method: :put if @story.can_finish?
  = link_to "Принять задачу", story_change_state_path(@story, event: :accept), method: :put if @story.can_accept?
  = link_to "Отклонить задачу", story_change_state_path(@story, event: :reject), method: :put if @story.can_reject? 


%h2 Comments:
%table{ :class => "table table-striped"} 
  %tr
    %td
      %strong
        = :user
    %td
      %strong
        = :comment
    - if author?(@story.user_id)
      %td

  - @story.story_comments.each do |story_comment|
    %tr
      %td 
        - user_id = story_comment.user_id
        = get_user_login(user_id)
      %td 
        = story_comment.comment
      -if author?(@story.user_id)
        %td
          = link_to 'Destroy Comment', [story_comment.story, story_comment], :method => :delete

-if signed_in?
  %h2 Add comment:
  = form_for([@story, @story.story_comments.build]) do |f|
    %p
    = f.label :comment
    %br
    = f.text_area :comment
    %br
    = f.submit
-if author?(@story.user_id)
  = link_to 'Edit', edit_story_path(@story)
  |
\#{link_to 'Back', stories_path}