config/routes.rb
TaskManager::Application.routes.draw do
  resources :stories do
    resources :story_comments
    put :change_state
  end

  resources :users
  resource :session, :only => [:new, :create, :destroy]

end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "TaskManager"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
    = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="images/favicon.ico" rel="shortcut icon")


  #user_nav
    - if signed_in?
      Здравствуйте, #{current_user.email}
      \#{link_to "Выйти", session_path, :method => :delete}
    - else
      \#{link_to "Зарегистрироваться", new_user_path}
      или
      \#{link_to "Войти", new_session_path}

  - flash.each do |name, msg|
    = content_tag :div, msg, :id => "flash_#{name}", :class => "alert"

  %body
    = yield

  = javascript_include_tag "application"